### ISSUE TITLE
Service for saving matching

### ISSUE THREAD

**Issue by emilie19** [bitem-heg-geneve/ebiodiv-matching-backend#1]
Saving of matching status doesn't work anymore:

{"data":null,"status":200,"statusText":"OK","headers":{"content-length":"5","content-type":"application/json"},"config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"method":"post","url":"https://candy.text-analytics.ch/ebiodiv/matching/api/v1/matching/materialcitation/3084918302","data":"{\"done\":false,\"specimens\":{\"3044002302\":{\"match\":true,\"comment\":\"\"}}}"},"request":{}}

**Comment by dalf** [comment]
Fixed in commit 6219e1d24fd109231ad17f3a34c4a0abda11092e
